# Generated by Django 3.2.9 on 2021-12-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelinheritanceconcept', '0002_examcenter_mbastudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExamCenter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modelinheritanceconcept.examcenter',),
        ),
    ]
