# Generated by Django 3.2.9 on 2021-12-11 08:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanagerconcept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyStudent',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modelmanagerconcept.student',),
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
    ]
