# Generated by Django 3.2.9 on 2021-12-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbasedvieww', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emailId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
