# Generated by Django 3.2.9 on 2021-12-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbasedvieww', '0002_student_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobileno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
