# Generated by Django 3.2.9 on 2021-12-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbasedvieww', '0003_student_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passout',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
