# Generated by Django 3.2.9 on 2021-12-23 16:51

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('classbasedvieww', '0004_student_passout'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passoutdate',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]
