# Generated by Django 3.2.9 on 2021-12-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelrelationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelrelationship.page')),
                ('likes', models.IntegerField()),
            ],
            bases=('modelrelationship.page',),
        ),
    ]
